-- CardSignal Supabase schema
-- Run this in Supabase SQL Editor after creating the project.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  email text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.user_state enable row level security;

create policy "profiles_select_own" on public.profiles
for select to authenticated using ((select auth.uid()) = id);

create policy "profiles_insert_own" on public.profiles
for insert to authenticated with check ((select auth.uid()) = id);

create policy "profiles_update_own" on public.profiles
for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy "state_select_own" on public.user_state
for select to authenticated using ((select auth.uid()) = user_id);

create policy "state_insert_own" on public.user_state
for insert to authenticated with check ((select auth.uid()) = user_id);

create policy "state_update_own" on public.user_state
for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, email)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'username',''), split_part(coalesce(new.email,'collector'),'@',1)),
    new.email
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

revoke execute on function public.handle_new_user() from public, anon, authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Durable market intelligence collected by scheduled server-side scans.
create table if not exists public.market_scan_runs (
  id uuid primary key default gen_random_uuid(),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running' check (status in ('running','completed','partial','failed')),
  users_seen integer not null default 0,
  cards_seen integer not null default 0,
  cards_scanned integer not null default 0,
  cards_failed integer not null default 0,
  details jsonb not null default '{}'::jsonb
);

create table if not exists public.market_snapshots (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.market_scan_runs(id) on delete set null,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_card_id bigint not null,
  player text not null,
  year text,
  set_name text,
  card_number text,
  variant text,
  grader text,
  grade text,
  scanned_at timestamptz not null default now(),
  accepted_count integer not null default 0,
  rejected_count integer not null default 0,
  current_median numeric,
  recent_median numeric,
  prior_median numeric,
  change_7d numeric,
  recent_sales integer not null default 0,
  velocity numeric,
  pulse text not null default 'NOT ENOUGH DATA',
  confidence text not null default 'LOW',
  source_status jsonb not null default '{}'::jsonb
);

create table if not exists public.market_sales (
  id bigint generated by default as identity primary key,
  snapshot_id uuid not null references public.market_snapshots(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_card_id bigint not null,
  provider text not null,
  provider_sale_id text,
  title text not null,
  sale_price numeric,
  sale_date timestamptz,
  marketplace text,
  raw jsonb not null default '{}'::jsonb
);

create table if not exists public.signal_events (
  id uuid primary key default gen_random_uuid(),
  snapshot_id uuid not null references public.market_snapshots(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_card_id bigint not null,
  created_at timestamptz not null default now(),
  signal_type text not null,
  confidence text not null,
  score numeric,
  explanation text,
  evidence jsonb not null default '{}'::jsonb
);

create table if not exists public.news_events (
  id bigint generated by default as identity primary key,
  event_key text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_card_id bigint not null,
  player text not null,
  title text not null,
  url text not null,
  domain text,
  published_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  category text not null,
  tone text not null check (tone in ('positive','negative','watch','neutral')),
  impact integer not null default 0 check (impact between 0 and 100),
  provider text not null,
  raw jsonb not null default '{}'::jsonb,
  unique (user_id, client_card_id, event_key)
);

create table if not exists public.supply_snapshots (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.market_scan_runs(id) on delete set null,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_card_id bigint not null,
  player text not null,
  scanned_at timestamptz not null default now(),
  provider text not null default 'eBay Browse API',
  query text,
  identity_confidence text not null default 'LOW',
  matching_version integer not null default 3,
  raw_total integer not null default 0,
  fetched_count integer not null default 0,
  accepted_count integer not null default 0,
  rejected_count integer not null default 0,
  lowest_ask numeric,
  median_ask numeric,
  highest_ask numeric,
  inventory_delta_pct numeric,
  median_ask_delta_pct numeric,
  ask_vs_sold_pct numeric,
  new_listing_count integer,
  disappeared_listing_count integer,
  supply_state text not null default 'BASELINE',
  listing_ids jsonb not null default '[]'::jsonb,
  listing_sample jsonb not null default '[]'::jsonb,
  source_status jsonb not null default '{}'::jsonb
);

create index if not exists market_snapshots_user_card_time_idx on public.market_snapshots(user_id, client_card_id, scanned_at desc);
create index if not exists market_snapshots_run_id_idx on public.market_snapshots(run_id);
create index if not exists market_sales_snapshot_idx on public.market_sales(snapshot_id);
create index if not exists market_sales_user_card_date_idx on public.market_sales(user_id, client_card_id, sale_date desc);
create index if not exists signal_events_user_card_time_idx on public.signal_events(user_id, client_card_id, created_at desc);
create index if not exists signal_events_snapshot_id_idx on public.signal_events(snapshot_id);
create index if not exists news_events_user_card_time_idx on public.news_events(user_id, client_card_id, published_at desc);
create index if not exists news_events_player_time_idx on public.news_events(player, published_at desc);
create index if not exists supply_snapshots_user_card_time_idx on public.supply_snapshots(user_id, client_card_id, scanned_at desc);
create index if not exists supply_snapshots_run_id_idx on public.supply_snapshots(run_id);

alter table public.market_scan_runs enable row level security;
alter table public.market_snapshots enable row level security;
alter table public.market_sales enable row level security;
alter table public.signal_events enable row level security;
alter table public.news_events enable row level security;
alter table public.supply_snapshots enable row level security;

drop policy if exists "market_snapshots_select_own" on public.market_snapshots;
create policy "market_snapshots_select_own" on public.market_snapshots for select to authenticated
using ((select auth.uid()) = user_id);
drop policy if exists "market_sales_select_own" on public.market_sales;
create policy "market_sales_select_own" on public.market_sales for select to authenticated
using ((select auth.uid()) = user_id);
drop policy if exists "signal_events_select_own" on public.signal_events;
create policy "signal_events_select_own" on public.signal_events for select to authenticated
using ((select auth.uid()) = user_id);
drop policy if exists "news_events_select_own" on public.news_events;
create policy "news_events_select_own" on public.news_events for select to authenticated
using ((select auth.uid()) = user_id);
drop policy if exists "supply_snapshots_select_own" on public.supply_snapshots;
create policy "supply_snapshots_select_own" on public.supply_snapshots for select to authenticated
using ((select auth.uid()) = user_id);

grant select on public.market_snapshots, public.market_sales, public.signal_events, public.news_events, public.supply_snapshots to authenticated;
grant all on public.market_scan_runs, public.market_snapshots, public.market_sales, public.signal_events, public.news_events, public.supply_snapshots to service_role;
grant usage, select on sequence public.market_sales_id_seq, public.news_events_id_seq to service_role;
