-- CardSignal sealed product catalog + market history.
-- Run once in the connected Supabase project.

create table if not exists public.sealed_products (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  canonical_key text not null,
  category text not null check (category in ('Sports','Pokémon')),
  year text,
  brand text,
  product_line text,
  format text not null,
  display_name text not null,
  msrp numeric,
  release_date date,
  identity_confidence text not null default 'low' check (identity_confidence in ('high','medium','low')),
  confirmed_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, canonical_key)
);

create table if not exists public.sealed_market_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sealed_product_id uuid not null references public.sealed_products(id) on delete cascade,
  scanned_at timestamptz not null default now(),
  provider text,
  market_median numeric,
  evidence_count integer not null default 0,
  priced_evidence_count integer not null default 0,
  last_sale_date timestamptz,
  sample_title text
);

create index if not exists sealed_products_user_idx on public.sealed_products(user_id, updated_at desc);
create index if not exists sealed_snapshots_product_idx on public.sealed_market_snapshots(sealed_product_id, scanned_at desc);
create index if not exists sealed_snapshots_user_idx on public.sealed_market_snapshots(user_id, scanned_at desc);

alter table public.sealed_products enable row level security;
alter table public.sealed_market_snapshots enable row level security;

drop policy if exists "sealed_products_own_rows" on public.sealed_products;
create policy "sealed_products_own_rows" on public.sealed_products
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "sealed_snapshots_own_rows" on public.sealed_market_snapshots;
create policy "sealed_snapshots_own_rows" on public.sealed_market_snapshots
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
