alter table public.sealed_products add column if not exists best_retail_price numeric;
alter table public.sealed_products add column if not exists best_retail_url text;
alter table public.sealed_products add column if not exists best_retail_source text;
alter table public.sealed_products add column if not exists best_retail_checked_at timestamptz;
alter table public.sealed_products add column if not exists retail_in_stock boolean;
alter table public.sealed_products add column if not exists last_restock_at timestamptz;

create table if not exists public.sealed_retail_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sealed_product_id uuid not null references public.sealed_products(id) on delete cascade,
  checked_at timestamptz not null default now(),
  source text not null,
  source_type text not null check (source_type in ('retailer','marketplace')),
  in_stock boolean not null default false,
  item_price numeric,
  shipping numeric,
  delivered_price numeric,
  url text,
  title text
);

create index if not exists sealed_retail_product_idx on public.sealed_retail_snapshots(sealed_product_id, checked_at desc);
create index if not exists sealed_retail_user_idx on public.sealed_retail_snapshots(user_id, checked_at desc);
alter table public.sealed_retail_snapshots enable row level security;
drop policy if exists "sealed_retail_own_rows" on public.sealed_retail_snapshots;
create policy "sealed_retail_own_rows" on public.sealed_retail_snapshots for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
