"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { addSealedLot, readSealedOwnership, type SealedCatalogProduct, type SealedPosition } from "./sealed-ownership-cloud";

function money(v:number|null){return v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(v)}
export default function SealedOwnership(){
 const[products,setProducts]=useState<SealedCatalogProduct[]>([]),[positions,setPositions]=useState<SealedPosition[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const[productId,setProductId]=useState(""),[quantity,setQuantity]=useState("1"),[unitCost,setUnitCost]=useState(""),[purchasedAt,setPurchasedAt]=useState(""),[retailer,setRetailer]=useState("");
 const refresh=()=>readSealedOwnership().then(d=>{setProducts(d.products);setPositions(d.positions);if(!productId&&d.products[0])setProductId(d.products[0].id)}).catch(()=>{}).finally(()=>setLoading(false));
 useEffect(()=>{refresh();const fn=()=>refresh();window.addEventListener("cardsignal-sealed-snapshot",fn);return()=>window.removeEventListener("cardsignal-sealed-snapshot",fn)},[]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");try{await addSealedLot({productId,quantity:Number(quantity),unitCost:Number(unitCost),purchasedAt,retailer});setMessage("Position added. Cost basis updated.");setQuantity("1");setUnitCost("");await refresh()}catch(err){setMessage(err instanceof Error?err.message:"Could not save position.")}finally{setSaving(false)}}
 const totals=useMemo(()=>positions.reduce((a,p)=>({cost:a.cost+p.totalCost,value:a.value+(p.marketValue||0),known:a.known+(p.marketValue==null?0:1)}),{cost:0,value:0,known:0}),[positions]);
 const pnl=totals.value-totals.cost;
 return <section className="sealed-own"><div className="sealed-own-inner">
  <div className="own-head"><div><span>SEALED PORTFOLIO</span><h2>Your actual boxes. Your actual cost basis.</h2><p>Add what you own and CardSignal turns generic market signals into position-aware ADD, HOLD, TAKE PROFIT, or REVIEW guidance.</p></div><b>{positions.length} POSITIONS</b></div>
  <div className="own-summary"><div><span>TOTAL COST</span><strong>{money(totals.cost)}</strong></div><div><span>CURRENT VALUE</span><strong>{totals.known?money(totals.value):"—"}</strong></div><div><span>UNREALIZED P/L</span><strong className={pnl>=0?"up":"down"}>{totals.known?`${pnl>=0?"+":""}${money(pnl)}`:"—"}</strong></div></div>
  <form onSubmit={submit} className="own-form"><select value={productId} onChange={e=>setProductId(e.target.value)} required><option value="">Select tracked sealed product…</option>{products.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select><input type="number" min="1" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="Qty"/><input type="number" min="0" step="0.01" value={unitCost} onChange={e=>setUnitCost(e.target.value)} placeholder="Cost each" required/><input type="date" value={purchasedAt} onChange={e=>setPurchasedAt(e.target.value)}/><input value={retailer} onChange={e=>setRetailer(e.target.value)} placeholder="Where bought (optional)"/><button disabled={saving||!productId}>{saving?"Saving…":"+ Add owned wax"}</button></form>{message&&<p className="own-message">{message}</p>}
  {loading?<div className="own-empty">Loading sealed positions…</div>:positions.length===0?<div className="own-empty">No sealed ownership yet. Confirm a sealed SKU, then add how many you own and what you paid.</div>:<div className="own-grid">{positions.map(p=><article key={p.productId}>{p.imageUrl?<div className="own-img"><img src={p.imageUrl} alt={p.displayName}/></div>:<div className="own-img placeholder">WAX</div>}<div className="own-copy"><span>{p.category} · {p.format}</span><h3>{p.displayName}</h3><div className="own-metrics"><div><small>OWN</small><b>{p.quantity}</b></div><div><small>AVG COST</small><b>{money(p.averageCost)}</b></div><div><small>MARKET EA.</small><b>{money(p.marketUnit)}</b></div><div><small>POSITION</small><b>{money(p.marketValue)}</b></div><div><small>P/L</small><b className={(p.unrealized||0)>=0?"up":"down"}>{p.unrealized==null?"—":`${p.unrealized>=0?"+":""}${money(p.unrealized)}`}</b></div><div><small>RETURN</small><b>{p.unrealizedPct==null?"—":`${p.unrealizedPct>=0?"+":""}${p.unrealizedPct.toFixed(1)}%`}</b></div></div><div className={`own-signal ${p.recommendation.toLowerCase().replace(" ","-")}`}><strong>{p.recommendation}</strong><p>{p.reason}</p></div></div></article>)}</div>}
 </div><style jsx>{`
 .sealed-own{background:#041019;color:#dceef4;border-bottom:1px solid rgba(83,200,230,.14);font-family:Arial,sans-serif}.sealed-own-inner{max-width:1360px;margin:0 auto;padding:22px 24px}.own-head{display:flex;justify-content:space-between;gap:20px}.own-head span{font-size:10px;font-weight:900;letter-spacing:.13em;color:#72e9b0}.own-head h2{font-size:21px;margin:5px 0}.own-head p{max-width:780px;margin:0;color:#7897a4;font-size:11px;line-height:1.5}.own-head>b{font-size:8px;color:#9cf0bd;border:1px solid rgba(100,230,160,.24);padding:7px 9px;border-radius:7px;height:max-content}.own-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0}.own-summary>div{background:#071b25;border:1px solid rgba(80,190,220,.1);padding:11px;border-radius:8px}.own-summary span,.own-metrics small{display:block;font-size:7px;color:#6f8994;font-weight:900;letter-spacing:.08em}.own-summary strong{font-size:17px}.up{color:#77efab!important}.down{color:#ef8e8e!important}.own-form{display:grid;grid-template-columns:2fr .55fr .8fr 1fr 1.2fr auto;gap:7px}.own-form input,.own-form select,.own-form button{min-height:38px;border-radius:7px;border:1px solid rgba(80,190,220,.17);background:#071a25;color:#d0e7ef;padding:0 10px}.own-form button{color:#96efb9;font-weight:900;cursor:pointer}.own-message{font-size:9px;color:#7fa892}.own-grid{display:grid;gap:9px;margin-top:14px}.own-grid article{display:grid;grid-template-columns:100px 1fr;gap:13px;background:#061925;border:1px solid rgba(90,190,220,.12);border-radius:9px;padding:12px}.own-img{height:92px;border-radius:7px;background:#031018;display:flex;align-items:center;justify-content:center;overflow:hidden}.own-img img{max-width:100%;max-height:100%;object-fit:contain}.own-img.placeholder{color:#526a73;font-size:10px;font-weight:900}.own-copy>span{font-size:8px;color:#62cde8;text-transform:uppercase}.own-copy h3{margin:3px 0 9px;font-size:14px}.own-metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:6px}.own-metrics>div{background:#04131d;border-radius:6px;padding:7px}.own-metrics b{display:block;margin-top:3px;font-size:11px}.own-signal{margin-top:8px;border-left:3px solid #6b8d98;background:#04131d;padding:8px 10px}.own-signal strong{font-size:10px}.own-signal p{margin:3px 0 0;color:#76909b;font-size:9px}.own-signal.add{border-color:#6ee7a6}.own-signal.take-profit{border-color:#ffc070}.own-signal.review{border-color:#ef9292}.own-empty{margin-top:12px;padding:13px;border:1px dashed rgba(90,180,205,.16);border-radius:8px;color:#7694a0;font-size:10px}@media(max-width:800px){.sealed-own-inner{padding:16px 14px}.own-head{display:block}.own-summary{grid-template-columns:1fr}.own-form{grid-template-columns:1fr 1fr}.own-form select,.own-form input:nth-of-type(3),.own-form button{grid-column:1/-1}.own-grid article{grid-template-columns:78px 1fr}.own-metrics{grid-template-columns:repeat(2,1fr)}}
 `}</style></section>}
