import { NextRequest, NextResponse } from "next/server";

type RetailOffer = { source:string; title:string; price:number; shipping:number; deliveredPrice:number; url:string; imageUrl?:string; inStock:boolean; seller?:string; sourceType:"retailer"|"marketplace" };
const NOISE=/\b(single|card only|pick your|break|case break|box break|team break|digital|code card|empty box|wrapper|repack|mystery pack|graded|psa|bgs|sgc|cgc|slab)\b/i;
function num(v:unknown){const n=Number.parseFloat(String(v??""));return Number.isFinite(n)?n:null}
function normalize(v:string){return v.toLowerCase().replace(/[–—]/g,"-").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim()}
function tokens(q:string){const ignore=new Set(["sealed","new","factory","box","pack","hobby","retail","trading","cards","card"]);return normalize(q).split(" ").filter(t=>t.length>2&&!ignore.has(t))}
function likelyMatch(q:string,title:string){if(NOISE.test(title))return false;const hay=normalize(title),need=tokens(q);if(!need.length)return false;return need.filter(t=>hay.includes(t)).length>=Math.max(2,Math.ceil(need.length*.65))}
function retailerLinks(q:string){const e=encodeURIComponent(q);return[
  {source:"Target",url:`https://www.target.com/s?searchTerm=${e}`},
  {source:"Walmart",url:`https://www.walmart.com/search?q=${e}`},
  {source:"GameStop",url:`https://www.gamestop.com/search/?q=${e}`},
  {source:"Best Buy",url:`https://www.bestbuy.com/site/searchpage.jsp?st=${e}`},
  {source:"Pokémon Center",url:`https://www.pokemoncenter.com/search/${e}`},
  {source:"Topps",url:`https://www.topps.com/pages/search-results?q=${e}`},
  {source:"Fanatics Collect",url:`https://www.fanaticscollect.com/search?q=${e}`},
]}
async function bestBuy(q:string):Promise<RetailOffer[]>{const key=process.env.BESTBUY_API_KEY?.trim();if(!key)return[];const search=tokens(q).slice(0,6).join("&search=");if(!search)return[];const url=`https://api.bestbuy.com/v1/products(search=${encodeURIComponent(tokens(q).slice(0,6).join(" "))})?apiKey=${encodeURIComponent(key)}&format=json&show=sku,name,salePrice,url,image,onlineAvailability`;try{const r=await fetch(url,{cache:"no-store"});if(!r.ok)return[];const j=await r.json() as {products?:Array<Record<string,unknown>>};return (j.products||[]).filter(p=>likelyMatch(q,String(p.name||""))).map(p=>({source:"Best Buy",title:String(p.name||q),price:num(p.salePrice)??0,shipping:0,deliveredPrice:num(p.salePrice)??0,url:String(p.url||""),imageUrl:String(p.image||""),inStock:Boolean(p.onlineAvailability),sourceType:"retailer" as const})).filter(o=>o.price>0&&o.url)}catch{return[]}}
async function ebay(request:NextRequest,q:string):Promise<RetailOffer[]>{try{const r=await fetch(`${request.nextUrl.origin}/api/sealed-best-offer?q=${encodeURIComponent(q)}`,{cache:"no-store"});const j=await r.json() as any;const b=j?.bestOffer;if(!r.ok||!j?.ok||!b?.url||!b?.deliveredPrice)return[];return[{source:"eBay",title:String(b.title||q),price:Number(b.price||0),shipping:Number(b.shipping||0),deliveredPrice:Number(b.deliveredPrice||0),url:String(b.url),imageUrl:String(b.imageUrl||""),inStock:true,seller:String(b.seller||""),sourceType:"marketplace"}]}catch{return[]}}
export async function GET(request:NextRequest){const sp=new URL(request.url).searchParams;const q=sp.get("q")?.trim()||"";const msrp=num(sp.get("msrp"));if(q.length<3)return NextResponse.json({ok:false,error:"Missing product query."},{status:400});const [bb,eb]=await Promise.all([bestBuy(q),ebay(request,q)]);const live=[...bb,...eb].filter(o=>o.inStock&&o.deliveredPrice>0).sort((a,b)=>a.deliveredPrice-b.deliveredPrice);const best=live[0]||null;return NextResponse.json({ok:true,query:q,checkedAt:new Date().toISOString(),msrp,liveOffers:live,bestLiveOffer:best,atOrBelowMsrp:Boolean(best&&msrp&&best.deliveredPrice<=msrp),savingsVsMsrp:best&&msrp?Math.round((msrp-best.deliveredPrice)*100)/100:null,retailerSearchLinks:retailerLinks(q),configuredSources:{ebay:Boolean(process.env.EBAY_CLIENT_ID&&process.env.EBAY_CLIENT_SECRET),bestBuy:Boolean(process.env.BESTBUY_API_KEY)},note:"Live price/stock is shown only for configured sources with machine-readable availability. Other retailer buttons are direct product searches and are not counted as verified in-stock offers."})}
