import { NextRequest, NextResponse } from "next/server";

type Sale = { source: "SoldComps" | "The Card API"; id: string; title: string; price: number | null; date: string; marketplace: string; grader?: string; grade?: string; url?: string; image?: string };
type Identity = { year?: string; setName?: string; manufacturer?: string; cardNumber?: string; playerName?: string; variation?: string; sport?: string; url?: string };
type Canonical = { player: string; year: string; setName: string; cardNumber: string; variant: string; grader: string; grade: string };

const VARIANTS=["logofractor","refractor","x-fractor","xfractor","superfractor","cosmic chrome","cosmic","sapphire","silver","holo","hyper","wave","shimmer","cracked ice","ice","scope","mojo","sepia","negative","pink","purple","blue","green","red","orange","gold","black","aqua","raywave","ray wave"];
function normalize(v:string){return v.toLowerCase().replace(/[–—]/g,"-").replace(/[^a-z0-9#/.+-]+/g," ").replace(/\s+/g," ").trim()}
function phraseIn(text:string,phrase:string){return ` ${normalize(text)} `.includes(` ${normalize(phrase)} `)}
function num(v:unknown){const n=typeof v==="number"?v:Number.parseFloat(String(v??""));return Number.isFinite(n)?n:null}
function median(v:number[]){if(!v.length)return null;const s=[...v].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2}
function stats(sales:Sale[]){const p=sales.map(s=>s.price).filter((v):v is number=>v!=null);if(!p.length)return{count:0,median:null,average:null,low:null,high:null};return{count:p.length,median:median(p),average:p.reduce((a,b)=>a+b,0)/p.length,low:Math.min(...p),high:Math.max(...p)}}
function extractNumber(t:string){return normalize(t).match(/#\s*([a-z0-9-]+)/)?.[1]??""}
function titleGrade(s:Sale){const t=normalize(s.title);const g=t.match(/\b(psa|bgs|sgc|cgc)\s*(10|9(?:\.5)?|8(?:\.5)?|7(?:\.5)?)\b/);return{grader:normalize(s.grader??g?.[1]??""),grade:normalize(s.grade??g?.[2]??"")}}
function baseIdentityMatch(c:Canonical,s:Sale,requireVariant=true){const t=normalize(s.title);const pt=normalize(c.player).split(" ").filter(x=>x.length>1);if(pt.length&&!pt.every(x=>t.includes(x)))return false;if(c.year){const y=t.match(/\b((?:19|20)\d{2})\b/)?.[1]??"";if(y&&y!==c.year.slice(0,4))return false}if(c.setName&&!phraseIn(t,c.setName))return false;if(c.cardNumber){const n=extractNumber(t);if(n&&normalize(n)!==normalize(c.cardNumber))return false}if(requireVariant&&c.variant&&!phraseIn(t,c.variant))return false;return true}
function exactMatch(c:Canonical,s:Sale){if(!baseIdentityMatch(c,s,true))return false;if(!c.variant&&VARIANTS.some(v=>phraseIn(s.title,v)))return false;if(c.grader||c.grade){const tg=titleGrade(s);if(c.grader&&tg.grader&&tg.grader!==normalize(c.grader))return false;if(c.grade&&tg.grade&&tg.grade!==normalize(c.grade))return false;if(c.grader&&!tg.grader&&!phraseIn(s.title,c.grader))return false;if(c.grade&&!tg.grade&&!new RegExp(`\\b${c.grade.replace(".","\\.")}\\b`).test(normalize(s.title)))return false}return true}
function relatedMatch(c:Canonical,s:Sale){if(!baseIdentityMatch(c,s,true))return false;if(exactMatch(c,s))return false;const tg=titleGrade(s);if(c.grade&&tg.grade){const a=Number.parseFloat(c.grade),b=Number.parseFloat(tg.grade);if(Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)<=1)return true}return !c.grade||!!tg.grade||/\braw\b/i.test(s.title)}
function referenceMatch(c:Canonical,s:Sale){if(exactMatch(c,s)||relatedMatch(c,s))return false;if(baseIdentityMatch(c,s,false))return true;const t=normalize(s.title);const pt=normalize(c.player).split(" ").filter(x=>x.length>1);return pt.every(x=>t.includes(x))&&(!c.year||t.includes(c.year.slice(0,4)))&&(!c.setName||phraseIn(t,c.setName))}
function dedupe(sales:Sale[]){const seen=new Set<string>();return sales.filter(s=>{const k=s.id?`${s.source}|${s.id}`:`${normalize(s.title).slice(0,100)}|${s.price}|${s.date.slice(0,10)}`;if(seen.has(k))return false;seen.add(k);return true})}
async function soldComps(q:string){const k=process.env.SOLD_COMPS_API_KEY?.trim();if(!k)return{ok:false,sales:[] as Sale[],error:"Missing SOLD_COMPS_API_KEY"};try{const r=await fetch(`https://api.sold-comps.com/v1/scrape?keyword=${encodeURIComponent(q)}&count=40&exactMatch=false`,{headers:{Accept:"application/json",Authorization:`Bearer ${k}`,"User-Agent":"CardSignal/0.1"},cache:"no-store"});const text=await r.text();let p:Record<string,unknown>={};try{p=JSON.parse(text)}catch{}if(!r.ok)return{ok:false,sales:[] as Sale[],error:String(p.error??p.message??text.slice(0,180))};const rows=Array.isArray(p.items)?p.items as Record<string,unknown>[]:[];return{ok:true,sales:rows.map(i=>({source:"SoldComps" as const,id:String(i.itemId??""),title:String(i.title??""),price:num(i.soldPrice),date:String(i.endedAt??""),marketplace:String(i.marketplace??"eBay"),url:String(i.url??""),image:String(i.thumbnailUrl??"")}))}}catch(e){return{ok:false,sales:[] as Sale[],error:e instanceof Error?e.message:"SoldComps failed"}}}
async function cardApi(q:string){const k=process.env.CARD_API_KEY?.trim();if(!k)return{ok:false,sales:[] as Sale[],error:"Missing CARD_API_KEY"};try{const r=await fetch(`https://thecardapi.com/api/v1/market/sales?q=${encodeURIComponent(q)}&limit=40`,{headers:{Accept:"application/json","x-market-api-key":k},cache:"no-store"});const text=await r.text();let p:Record<string,unknown>={};try{p=JSON.parse(text)}catch{}if(!r.ok)return{ok:false,sales:[] as Sale[],error:String(p.error??p.message??text.slice(0,180))};const rows=Array.isArray(p.data)?p.data as Record<string,unknown>[]:[];return{ok:true,sales:rows.map(i=>({source:"The Card API" as const,id:String(i.id??""),title:String(i.title??""),price:num(i.price??i.sale_price),date:String(i.sale_date??i.sold_at??""),marketplace:String(i.platform??"eBay"),grader:String(i.grader??i.grading_company??""),grade:String(i.grade??""),url:String(i.listing_url??""),image:String(i.thumbnail_url??i.image_url??"")}))}}catch(e){return{ok:false,sales:[] as Sale[],error:e instanceof Error?e.message:"Card API failed"}}}
async function tcdb(c:Canonical){const k=process.env.PARSE_API_KEY?.trim();if(!k)return{ok:false,identities:[] as Identity[],error:"Missing PARSE_API_KEY"};const qs=new URLSearchParams({query:c.player});if(c.year)qs.set("year",c.year);if(c.setName)qs.set("set_name",c.setName);try{const r=await fetch(`https://api.parse.bot/scraper/123aeda8-4611-4871-a592-2109a3f6434f/search_cards?${qs.toString()}`,{headers:{Accept:"application/json","X-API-Key":k},cache:"no-store"});const text=await r.text();let p:Record<string,unknown>={};try{p=JSON.parse(text)}catch{}if(!r.ok)return{ok:false,identities:[] as Identity[],error:String(p.error??p.message??text.slice(0,180))};const root=(p.data&&typeof p.data==="object")?p.data as Record<string,unknown>:p;const rows=Array.isArray(root.results)?root.results as Record<string,unknown>[]:Array.isArray(root.cards)?root.cards as Record<string,unknown>[]:[];return{ok:true,identities:rows.map(row=>({year:String(row.year??""),setName:String(row.set_name??row.setName??""),manufacturer:String(row.manufacturer??""),cardNumber:String(row.card_number??row.number??""),playerName:String(row.player_name??row.name??""),variation:String(row.parallel_variation??row.variation??""),sport:String(row.sport??""),url:String(row.url??"")})).slice(0,12)}}catch(e){return{ok:false,identities:[] as Identity[],error:e instanceof Error?e.message:"TCDB failed"}}}

export async function GET(request:NextRequest){const sp=new URL(request.url).searchParams,q=sp.get("q")?.trim()??"",player=sp.get("player")?.trim()??"";if(!q||!player)return NextResponse.json({ok:false,error:"Exact card selection required"},{status:400});const grader=normalize(q).match(/\b(psa|bgs|sgc|cgc)\b/)?.[1]??"",grade=grader?normalize(q).match(new RegExp(`\\b${grader}\\s*(10|9(?:\\.5)?|8(?:\\.5)?|7(?:\\.5)?)\\b`))?.[1]??"":"";const c:Canonical={player,year:sp.get("year")?.trim()??"",setName:sp.get("set")?.trim()??"",cardNumber:sp.get("cardNumber")?.trim()??"",variant:sp.get("variant")?.trim()??"",grader,grade};const exactQuery=[c.player,c.year,c.setName,c.cardNumber?`#${c.cardNumber}`:"",c.variant,c.grader?`${c.grader.toUpperCase()} ${c.grade}`:""].filter(Boolean).join(" ");const started=Date.now();const[sold,card,catalog]=await Promise.all([soldComps(exactQuery),cardApi(exactQuery),tcdb(c)]);const raw=dedupe([...sold.sales,...card.sales]);const exact=raw.filter(s=>exactMatch(c,s));const related=raw.filter(s=>relatedMatch(c,s));const reference=raw.filter(s=>referenceMatch(c,s));const exactStats=stats(exact),relatedStats=stats(related),referenceStats=stats(reference);const bySource=(source:Sale["source"])=>{const e=exact.filter(s=>s.source===source);return{rejected:raw.filter(s=>s.source===source).length-e.length,...stats(e)}};const med=[bySource("SoldComps").median,bySource("The Card API").median].filter((v):v is number=>v!=null&&v>0),diff=med.length===2?Math.abs(med[0]-med[1])/((med[0]+med[1])/2)*100:null,agreement=diff==null?"Single source":diff<=12?"High":diff<=25?"Moderate":"Low";return NextResponse.json({ok:sold.ok||card.ok||catalog.ok,query:q,canonical:c,elapsedMs:Date.now()-started,identity:{provider:"TCDB / Parse",ok:catalog.ok,error:catalog.error??null,candidates:catalog.identities},market:{merged:exactStats,sourceAgreement:agreement,disagreementPct:diff==null?null:Math.round(diff*10)/10,sources:{soldComps:{ok:sold.ok,error:sold.error??null,rawCount:sold.sales.length,...bySource("SoldComps")},cardApi:{ok:card.ok,error:card.error??null,rawCount:card.sales.length,...bySource("The Card API")}},sales:exact.map(s=>({...s,tier:"Exact"})).slice(0,40),tiers:{exact:{...exactStats,sales:exact.slice(0,12)},related:{...relatedStats,sales:related.slice(0,12)},reference:{...referenceStats,sales:reference.slice(0,12)}}}})}
