"use client";

import {useEffect,useState} from "react";
import {createPortal} from "react-dom";
import {cloudConfigured,readCloudState,readSession,refreshSession,writeCloudState} from "./cloud-client";

const SYNC_KEYS=["cardsignal-added-cards","cardsignal-scan-history","cardsignal-longitudinal-scan-history","cardsignal-portfolio-history","cardsignal-alerts","cardsignal-catalysts","cardsignal-catalyst-history","cardsignal-supply-history","cardsignal-grading-population-history","cardsignal-player-performance-history","cardsignal-discovery-scouts","cardsignal-discovery-results","cardsignal-discovery-settings","cardsignal-market-scout-results","cardsignal-market-scout-settings","cardsignal-decision-journal","cardsignal-reviewed-actions","cardsignal-pokemon-cards","cardsignal-pokemon-price-history","cardsignal-signal-observations"];
const SYNC_META="cardsignal-cloud-sync-meta";
type Payload={version:number;values:Record<string,string|null>};
type SyncMeta={userId?:string;lastSync?:string};
function capture():Payload{return{version:1,values:Object.fromEntries(SYNC_KEYS.map(k=>[k,localStorage.getItem(k)]))}}
function restore(p:Payload){for(const k of SYNC_KEYS){const v=p?.values?.[k];if(v==null)localStorage.removeItem(k);else localStorage.setItem(k,v)}window.dispatchEvent(new Event("cardsignal:user-cards-changed"));window.dispatchEvent(new Event("cardsignal:cloud-restored"));}
function signature(p:Payload){return JSON.stringify(p.values)}
function meta():SyncMeta|null{try{return JSON.parse(localStorage.getItem(SYNC_META)||"null") as SyncMeta|null}catch{return null}}
function hasData(p:Payload){return Object.values(p.values).some(Boolean)}
function isolatePriorLocal(previousUserId?:string){const p=capture();if(!hasData(p))return;const label=(previousUserId||"unassigned").replace(/[^a-zA-Z0-9_-]/g,"_");try{localStorage.setItem(`cardsignal-local-quarantine-${label}-${Date.now()}`,JSON.stringify(p))}catch{}for(const k of SYNC_KEYS)localStorage.removeItem(k);window.dispatchEvent(new Event("cardsignal:user-cards-changed"));}

export default function CloudSyncLayer(){
 const[ready,setReady]=useState(false),[state,setState]=useState<"idle"|"choose"|"syncing"|"synced"|"error">("idle"),[message,setMessage]=useState(""),[cloudUpdated,setCloudUpdated]=useState("");
 useEffect(()=>{if(!cloudConfigured())return;let cancelled=false;let timer:number|undefined;let lastSig="";
  const boot=async()=>{try{const s=await refreshSession();if(!s||cancelled){setReady(true);return}const remote=await readCloudState(s.access_token);if(cancelled)return;setCloudUpdated(remote?.updated_at||"");let local=capture();const m=meta(),sameUser=!!m?.userId&&m.userId===s.user.id,differentKnownUser=!!m?.userId&&m.userId!==s.user.id;
    if(differentKnownUser){isolatePriorLocal(m?.userId);local=capture();setMessage("Local data from the previously signed-in account was isolated before loading this account.");}
    const localHas=hasData(local);
    if(remote?.payload){const remotePayload=remote.payload as Payload;if(!sameUser&&!differentKnownUser&&localHas&&!m){setState("choose");setMessage("This device already has unassigned CardSignal data and this account also has cloud data. Choose which copy should win.");}else{restore(remotePayload);lastSig=signature(remotePayload);localStorage.setItem(SYNC_META,JSON.stringify({userId:s.user.id,lastSync:new Date().toISOString()}));setState("synced");}}
    else if(localHas&&!differentKnownUser&&!m){setState("choose");setMessage("This account has no cloud collection yet. Import the unassigned CardSignal data currently saved on this device?");}
    else if(localHas&&sameUser){setState("choose");setMessage("This account has no cloud collection yet. Save this account's local CardSignal data to the cloud?");}
    else{lastSig=signature(capture());localStorage.setItem(SYNC_META,JSON.stringify({userId:s.user.id,lastSync:new Date().toISOString()}));setState("synced");}
    timer=window.setInterval(async()=>{try{const live=await refreshSession();if(!live)return;const currentMeta=meta();if(currentMeta?.userId&&currentMeta.userId!==live.user.id)return;const p=capture(),sig=signature(p);if(sig===lastSig)return;await writeCloudState(live.access_token,live.user.id,p as unknown as Record<string,unknown>);lastSig=sig;localStorage.setItem(SYNC_META,JSON.stringify({userId:live.user.id,lastSync:new Date().toISOString()}));setState("synced");}catch{}},4000);
  }catch(e){setState("error");setMessage(e instanceof Error?e.message:"Cloud sync failed")}finally{setReady(true)}};
  boot();const auth=()=>{if(timer)window.clearInterval(timer);setReady(false);setState("idle");window.setTimeout(()=>boot(),50)};window.addEventListener("cardsignal:cloud-auth-changed",auth);return()=>{cancelled=true;if(timer)window.clearInterval(timer);window.removeEventListener("cardsignal:cloud-auth-changed",auth)}
 },[]);
 const importLocal=async()=>{setState("syncing");setMessage("");try{const s=readSession();if(!s)throw new Error("Sign in first.");const currentMeta=meta();if(currentMeta?.userId&&currentMeta.userId!==s.user.id)throw new Error("Local data belongs to a different signed-in account and will not be imported.");const p=capture();await writeCloudState(s.access_token,s.user.id,p as unknown as Record<string,unknown>);localStorage.setItem(SYNC_META,JSON.stringify({userId:s.user.id,lastSync:new Date().toISOString()}));setState("synced");setMessage("This account's local collection is now saved to its cloud account.");}catch(e){setState("error");setMessage(e instanceof Error?e.message:"Import failed")}};
 const useCloud=async()=>{setState("syncing");setMessage("");try{const s=readSession();if(!s)throw new Error("Sign in first.");const currentMeta=meta();if(currentMeta?.userId&&currentMeta.userId!==s.user.id)isolatePriorLocal(currentMeta.userId);const remote=await readCloudState(s.access_token);if(!remote?.payload)throw new Error("No cloud collection exists yet.");restore(remote.payload as Payload);localStorage.setItem(SYNC_META,JSON.stringify({userId:s.user.id,lastSync:new Date().toISOString()}));setState("synced");setMessage("Cloud collection loaded on this device.");}catch(e){setState("error");setMessage(e instanceof Error?e.message:"Cloud restore failed")}};
 if(!ready||!cloudConfigured())return null;
 return createPortal(<>{state==="choose"&&<div className="cs-sync-banner"><div><b>CLOUD COLLECTION SETUP</b><span>{message}</span>{cloudUpdated&&<small>Cloud copy last updated {new Date(cloudUpdated).toLocaleString()}</small>}</div><button onClick={importLocal}>USE THIS DEVICE</button><button onClick={useCloud}>LOAD CLOUD COPY</button></div>}{state==="syncing"&&<div className="cs-sync-toast">SYNCING CLOUD COLLECTION…</div>}{state==="error"&&<div className="cs-sync-toast error">{message}</div>}<style jsx global>{`.cs-sync-banner{position:fixed;left:50%;top:16px;transform:translateX(-50%);z-index:2600;width:min(820px,94vw);display:grid;grid-template-columns:1fr auto auto;gap:10px;align-items:center;padding:12px;border:1px solid rgba(103,222,255,.25);border-radius:10px;background:rgba(4,20,31,.97);box-shadow:0 18px 55px rgba(0,0,0,.48);color:#e4f8ff}.cs-sync-banner b,.cs-sync-banner span,.cs-sync-banner small{display:block}.cs-sync-banner b{color:#79e3ff;font-size:8px;letter-spacing:.1em}.cs-sync-banner span{margin-top:3px;color:#91aebb;font-size:8px}.cs-sync-banner small{margin-top:3px;color:#617f8d;font-size:6px}.cs-sync-banner button{height:34px;padding:0 10px;border:1px solid rgba(89,233,157,.25);border-radius:7px;background:#071724;color:#96f9bd;font-size:7px;font-weight:900;cursor:pointer}.cs-sync-banner button:last-child{border-color:rgba(93,205,244,.25);color:#95e5ff}.cs-sync-toast{position:fixed;left:50%;bottom:22px;transform:translateX(-50%);z-index:2600;padding:9px 12px;border:1px solid rgba(89,233,157,.22);border-radius:8px;background:#061721;color:#9cf8bf;font-size:7px;font-weight:900;letter-spacing:.08em}.cs-sync-toast.error{border-color:rgba(255,100,120,.25);color:#ff9baa}@media(max-width:720px){.cs-sync-banner{grid-template-columns:1fr}.cs-sync-banner button{width:100%}}`}</style></>,document.body)}
