"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";

type Scout={name:string;addedAt:string};
type Identity={year?:string;setName?:string;manufacturer?:string;cardNumber?:string;playerName?:string;variation?:string;sport?:string;cardId?:string;source?:string};
type Article={title:string;url:string;domain:string;publishedAt:string;category:string;tone:"positive"|"negative"|"watch"|"neutral";impact:number};
type CatalystResult={ok:boolean;player?:string;fetchedAt?:string;articles?:Article[];error?:string};
type SuggestionResult={ok:boolean;suggestions?:Identity[];source?:string};
type ExactResult={ok:boolean;market?:{merged?:{count?:number;median?:number|null;low?:number|null;high?:number|null};sourceAgreement?:string};error?:string};
type DiscoveryCard={id:string;player:string;year:string;setName:string;cardNumber:string;variation:string;median:number;low:number|null;high:number|null;compCount:number;agreement:string;catalyst:Article;signal:"DISCOVERY BUY WATCH"|"AVOID / NEGATIVE CATALYST";scannedAt:string};

type Settings={minPrice:number;maxPrice:number;minComps:number;minCatalystImpact:number};
const SCOUT_KEY="cardsignal-discovery-scouts",RESULT_KEY="cardsignal-discovery-results",SETTINGS_KEY="cardsignal-discovery-settings",CARD_KEY="cardsignal-added-cards",MAX_CARDS=500;
const DEFAULTS:Settings={minPrice:40,maxPrice:200,minComps:3,minCatalystImpact:70};
function readJson<T>(key:string,fallback:T):T{try{const v=JSON.parse(localStorage.getItem(key)||"");return(v??fallback)as T}catch{return fallback}}
function money(v:number|null|undefined){return v==null?"—":`$${v.toLocaleString(undefined,{maximumFractionDigits:2})}`}
function norm(v:string){return v.trim().toLowerCase()}
function cardKey(i:Identity){return [i.playerName,i.year,i.setName,i.cardNumber,i.variation].map(x=>String(x||"").trim().toLowerCase()).join("|")}
function savedCardKey(c:Record<string,unknown>){return [c.player,c.year,c.setName,c.cardNumber,c.variant].map(x=>String(x||"").trim().toLowerCase()).join("|")}

export default function DiscoveryRadarLayer(){
 const[ready,setReady]=useState(false),[open,setOpen]=useState(false),[scouts,setScouts]=useState<Scout[]>([]),[results,setResults]=useState<DiscoveryCard[]>([]),[settings,setSettings]=useState<Settings>(DEFAULTS),[name,setName]=useState(""),[running,setRunning]=useState(false),[progress,setProgress]=useState(""),[error,setError]=useState("");
 const refresh=()=>{setScouts(readJson<Scout[]>(SCOUT_KEY,[]));setResults(readJson<DiscoveryCard[]>(RESULT_KEY,[]));setSettings({...DEFAULTS,...readJson<Partial<Settings>>(SETTINGS_KEY,{})})};
 useEffect(()=>{setReady(true);refresh();const h=()=>setOpen(true);window.addEventListener("cardsignal:open-discovery",h);return()=>window.removeEventListener("cardsignal:open-discovery",h)},[]);
 const saveSettings=(next:Settings)=>{setSettings(next);localStorage.setItem(SETTINGS_KEY,JSON.stringify(next))};
 const addScout=()=>{const n=name.trim();if(!n)return;const next=[...scouts.filter(s=>norm(s.name)!==norm(n)),{name:n,addedAt:new Date().toISOString()}];setScouts(next);localStorage.setItem(SCOUT_KEY,JSON.stringify(next));setName("")};
 const removeScout=(n:string)=>{const next=scouts.filter(s=>norm(s.name)!==norm(n));setScouts(next);localStorage.setItem(SCOUT_KEY,JSON.stringify(next))};
 const notify=(row:DiscoveryCard)=>{if(typeof Notification==="undefined"||Notification.permission!=="granted")return;new Notification(`CardSignal: ${row.player} buy watch`,{body:`${row.year} ${row.setName} #${row.cardNumber||"—"} around ${money(row.median)} · ${row.catalyst.category}. Consider adding to portfolio.`})};
 const requestNotifications=async()=>{if(typeof Notification==="undefined"){setError("Browser notifications are not supported here.");return}const p=await Notification.requestPermission();if(p!=="granted")setError("Notification permission was not granted.");else setError("")};
 const scanPlayer=async(player:string)=>{
  const catRes=await fetch(`/api/catalysts?player=${encodeURIComponent(player)}`,{cache:"no-store"});const cat=await catRes.json() as CatalystResult;
  if(!catRes.ok||!cat.ok)return [] as DiscoveryCard[];
  const catalyst=(cat.articles||[]).filter(a=>a.impact>=settings.minCatalystImpact).sort((a,b)=>b.impact-a.impact)[0];
  if(!catalyst||catalyst.tone==="negative")return [] as DiscoveryCard[];
  const sugRes=await fetch(`/api/card-suggestions?q=${encodeURIComponent(player)}`,{cache:"no-store"});const sug=await sugRes.json() as SuggestionResult;
  const seen=new Set<string>();const identities=(sug.suggestions||[]).filter(i=>{const k=cardKey(i);if(!i.playerName||seen.has(k))return false;seen.add(k);return true}).slice(0,8);
  const found:DiscoveryCard[]=[];
  for(const i of identities){
   const q=[i.playerName||player,i.year,i.setName,i.cardNumber?`#${i.cardNumber}`:"",i.variation].filter(Boolean).join(" ");
   const p=new URLSearchParams({q,player:i.playerName||player,year:i.year||"",set:i.setName||"",cardNumber:i.cardNumber||"",variant:i.variation||""});
   try{const r=await fetch(`/api/signal-lab-exact?${p.toString()}`,{cache:"no-store"});const j=await r.json() as ExactResult;if(!r.ok||!j.ok)continue;const m=j.market?.merged,median=Number(m?.median||0),count=Number(m?.count||0);if(!median||count<settings.minComps||median<settings.minPrice||median>settings.maxPrice)continue;found.push({id:cardKey(i),player:i.playerName||player,year:i.year||"",setName:i.setName||"",cardNumber:i.cardNumber||"",variation:i.variation||"",median,low:m?.low??null,high:m?.high??null,compCount:count,agreement:j.market?.sourceAgreement||"Unknown",catalyst,signal:"DISCOVERY BUY WATCH",scannedAt:new Date().toISOString()})}catch{}
   if(found.length>=4)break;
  }
  return found;
 };
 const scanAll=async()=>{if(running)return;setRunning(true);setError("");const all:DiscoveryCard[]=[];for(let i=0;i<scouts.length;i++){setProgress(`${i+1} / ${scouts.length} · ${scouts[i].name}`);try{all.push(...await scanPlayer(scouts[i].name))}catch{} }const dedup=all.filter((x,i,a)=>i===a.findIndex(y=>y.id===x.id)).sort((a,b)=>b.catalyst.impact-a.catalyst.impact||b.compCount-a.compCount);setResults(dedup);localStorage.setItem(RESULT_KEY,JSON.stringify(dedup.slice(0,100)));dedup.slice(0,5).forEach(notify);setProgress(`Complete · ${dedup.length} buy-watch candidate${dedup.length===1?"":"s"}`);setRunning(false)};
 const addToWatchlist=(row:DiscoveryCard)=>{const cards=readJson<Array<Record<string,unknown>>>(CARD_KEY,[]);const candidateKey=[row.player,row.year,row.setName,row.cardNumber,row.variation].map(x=>String(x||"").trim().toLowerCase()).join("|");if(cards.some(c=>savedCardKey(c)===candidateKey))return;const id=Date.now()+Math.floor(Math.random()*1000);const meta=[row.year,row.setName,row.cardNumber&&`#${row.cardNumber}`,row.variation].filter(Boolean).join(" · ");const canonicalIdentity={playerName:row.player,year:row.year,setName:row.setName,cardNumber:row.cardNumber,variation:row.variation};const card={id,player:row.player,meta,year:row.year,setName:row.setName,cardNumber:row.cardNumber,variant:row.variation,mode:"watching",marketValue:row.median,score:0,move:"DISCOVERY",tone:"hold",addedAt:new Date().toISOString(),canonicalIdentity,discoverySource:{signal:row.signal,catalyst:row.catalyst,discoveredAt:row.scannedAt}};const next=[card,...cards].slice(0,MAX_CARDS);localStorage.setItem(CARD_KEY,JSON.stringify(next));window.dispatchEvent(new Event("cardsignal:user-cards-changed"))};
 const filtered=useMemo(()=>results.filter(r=>r.median>=settings.minPrice&&r.median<=settings.maxPrice),[results,settings]);
 if(!ready)return null;
 return createPortal(<>
  <button className="cs-discovery-launch" onClick={()=>{refresh();setOpen(true)}}>⌖ DISCOVERY</button>
  {open&&<div className="cs-disc-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="cs-disc-modal"><button className="cs-disc-close" onClick={()=>setOpen(false)}>×</button>
   <div className="cs-disc-head"><span>OUT-OF-PORTFOLIO SCOUT</span><h2>Discovery Radar</h2><p>Track players you do not own. CardSignal checks strong recent catalysts, discovers exact card identities, verifies sold comps, and only surfaces candidates inside your price band.</p></div>
   <div className="cs-disc-settings"><label><span>MIN PRICE</span><input type="number" min="0" value={settings.minPrice} onChange={e=>saveSettings({...settings,minPrice:Number(e.target.value||0)})}/></label><label><span>MAX PRICE</span><input type="number" min="1" value={settings.maxPrice} onChange={e=>saveSettings({...settings,maxPrice:Number(e.target.value||0)})}/></label><label><span>MIN SOLD COMPS</span><input type="number" min="1" value={settings.minComps} onChange={e=>saveSettings({...settings,minComps:Number(e.target.value||1)})}/></label><label><span>MIN CATALYST IMPACT</span><input type="number" min="0" max="100" value={settings.minCatalystImpact} onChange={e=>saveSettings({...settings,minCatalystImpact:Number(e.target.value||0)})}/></label><button onClick={requestNotifications}>ENABLE ALERTS</button></div>
   <div className="cs-disc-scout-add"><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addScout()} placeholder="Add player to scout — e.g. Caitlin Clark"/><button onClick={addScout}>ADD PLAYER</button><button className="scan" onClick={scanAll} disabled={running||!scouts.length}>{running?"SCANNING…":"SCAN DISCOVERY RADAR"}</button><span>{progress}</span></div>
   <div className="cs-disc-scouts">{scouts.length?scouts.map(s=><button key={s.name} onClick={()=>removeScout(s.name)} title="Remove from discovery scouts">{s.name}<i>×</i></button>):<span>No discovery players yet. Add players you want CardSignal to scout outside your collection.</span>}</div>
   {error&&<div className="cs-disc-error">{error}</div>}
   <div className="cs-disc-results">{filtered.length?filtered.map(row=><article key={row.id}><div className="cs-disc-signal"><span>{row.signal}</span><b>{row.catalyst.impact}</b><small>{row.catalyst.category}</small></div><div className="cs-disc-card"><strong>{row.player}</strong><span>{[row.year,row.setName,row.cardNumber&&`#${row.cardNumber}`,row.variation].filter(Boolean).join(" · ")}</span><p>{row.catalyst.title}</p></div><div className="cs-disc-market"><small>VERIFIED MEDIAN</small><b>{money(row.median)}</b><span>{row.compCount} exact sold comps · {row.agreement} agreement</span><em>{money(row.low)}–{money(row.high)}</em></div><button onClick={()=>addToWatchlist(row)}>＋ ADD TO WATCHLIST</button></article>):<div className="cs-disc-empty"><b>No buy-watch candidates in your current band</b><span>Run a scan after adding discovery players. Negative catalysts and cards outside {money(settings.minPrice)}–{money(settings.maxPrice)} are intentionally filtered out.</span></div>}</div>
   <div className="cs-disc-note">A Discovery Buy Watch means: strong non-negative catalyst + identifiable card + enough exact sold comps + current median inside your price limits. It is not yet the same as a portfolio BUY MORE signal because CardSignal has not accumulated price/velocity history for a newly discovered card. Browser alerts work while the site/browser can receive notifications; true background push will require the deployed scheduled-scanning service.</div>
  </section></div>}
  <style jsx global>{`
   .cs-discovery-launch{position:fixed;left:24px;bottom:24px;z-index:896;height:38px;padding:0 14px;border:1px solid rgba(95,219,255,.24);border-radius:8px;background:#071724;color:#8fe3ff;font-size:9px;font-weight:900;letter-spacing:.08em;cursor:pointer}
   .cs-disc-backdrop{position:fixed;inset:0;z-index:1660;display:grid;place-items:center;padding:22px;background:rgba(0,7,12,.88);backdrop-filter:blur(15px)}.cs-disc-modal{position:relative;width:min(1240px,98vw);max-height:94vh;overflow:auto;padding:28px;border:1px solid rgba(79,201,243,.2);border-radius:18px;background:linear-gradient(155deg,#081d2e,#04111d 64%,#061821);box-shadow:0 42px 120px rgba(0,0,0,.72);color:#effaff}.cs-disc-close{position:absolute;right:16px;top:14px;width:34px;height:34px;border:1px solid rgba(100,189,225,.16);border-radius:8px;background:#071724;color:#8cabbd;font-size:24px;cursor:pointer}.cs-disc-head>span{color:#59ddff;font-size:9px;font-weight:900;letter-spacing:.16em}.cs-disc-head h2{margin:7px 0 5px;font-size:30px}.cs-disc-head p{margin:0;max-width:880px;color:#7897a7;font-size:11px;line-height:1.5}
   .cs-disc-settings{display:grid;grid-template-columns:repeat(4,150px) auto;gap:8px;align-items:end;margin:18px 0}.cs-disc-settings label span{display:block;margin-bottom:4px;color:#648696;font-size:7px;font-weight:900}.cs-disc-settings input,.cs-disc-scout-add input{width:100%;height:36px;padding:0 10px;border:1px solid rgba(79,188,228,.14);border-radius:7px;background:#061724;color:#dff6ff;outline:none}.cs-disc-settings button,.cs-disc-scout-add button,.cs-disc-results article>button{height:36px;padding:0 12px;border:1px solid rgba(80,211,248,.2);border-radius:7px;background:#071724;color:#8fe3ff;font-size:8px;font-weight:900;cursor:pointer}.cs-disc-scout-add{display:grid;grid-template-columns:minmax(260px,1fr) 110px 165px auto;gap:8px;align-items:center}.cs-disc-scout-add .scan{color:#8cf5b8;border-color:rgba(89,236,159,.25)}.cs-disc-scout-add span{color:#6e8d9d;font-size:8px}.cs-disc-scouts{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0 15px}.cs-disc-scouts button{height:28px;padding:0 9px;border:1px solid rgba(81,190,230,.14);border-radius:999px;background:rgba(7,25,39,.7);color:#9bbbc9;font-size:8px;cursor:pointer}.cs-disc-scouts button i{margin-left:6px;color:#ff8795;font-style:normal}.cs-disc-scouts>span{color:#6e8d9d;font-size:8px}.cs-disc-error{margin:8px 0;padding:9px;border:1px solid rgba(255,100,120,.24);border-radius:8px;color:#ff9cab;font-size:8px;background:rgba(160,35,50,.1)}
   .cs-disc-results{display:flex;flex-direction:column;gap:7px}.cs-disc-results article{display:grid;grid-template-columns:150px minmax(280px,1fr) 230px 145px;gap:12px;align-items:center;padding:12px;border:1px solid rgba(78,184,224,.1);border-left:3px solid #59eca2;border-radius:10px;background:rgba(5,20,32,.62)}.cs-disc-signal span,.cs-disc-signal b,.cs-disc-signal small,.cs-disc-card strong,.cs-disc-card span,.cs-disc-card p,.cs-disc-market small,.cs-disc-market b,.cs-disc-market span,.cs-disc-market em{display:block}.cs-disc-signal span{color:#64efa7;font-size:7px;font-weight:900;letter-spacing:.07em}.cs-disc-signal b{margin-top:5px;font-size:20px;color:#79dff6}.cs-disc-signal small{color:#718f9f;font-size:7px}.cs-disc-card strong{font-size:13px}.cs-disc-card span{margin-top:3px;color:#7897a7;font-size:8px}.cs-disc-card p{margin:6px 0 0;color:#8da7b4;font-size:8px;line-height:1.4}.cs-disc-market small{color:#628292;font-size:6px;font-weight:900}.cs-disc-market b{margin-top:4px;font-size:17px}.cs-disc-market span,.cs-disc-market em{margin-top:3px;color:#718f9f;font-size:7px;font-style:normal}.cs-disc-results article>button{color:#8cf5b8;border-color:rgba(89,236,159,.25)}.cs-disc-empty{padding:45px;text-align:center;border:1px dashed rgba(76,184,224,.13);border-radius:10px}.cs-disc-empty b,.cs-disc-empty span{display:block}.cs-disc-empty b{font-size:12px}.cs-disc-empty span{margin:6px auto 0;max-width:650px;color:#718f9f;font-size:9px;line-height:1.5}.cs-disc-note{margin-top:12px;padding-top:10px;border-top:1px solid rgba(76,184,224,.08);color:#5f7f90;font-size:7px;line-height:1.5}@media(max-width:900px){.cs-disc-settings{grid-template-columns:1fr 1fr}.cs-disc-scout-add{grid-template-columns:1fr 110px}.cs-disc-scout-add .scan,.cs-disc-scout-add span{grid-column:1/-1}.cs-disc-results article{grid-template-columns:1fr 1fr}.cs-disc-results article>button{width:150px}}@media(max-width:600px){.cs-disc-modal{padding:22px 12px}.cs-disc-settings,.cs-disc-scout-add,.cs-disc-results article{grid-template-columns:1fr}}
  `}</style>
 </>,document.body);
}
