"use client";

import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";
import {nearestTrend,populationTrend,readPopulationHistory,writePopulationHistory,type GradingProvider,type PopulationSnapshot} from "./grading-population-model";

type Card={id:number;player:string;meta?:string;grader?:string;grade?:string};
const CARD_KEY="cardsignal-added-cards";
function readCards():Card[]{try{const v=JSON.parse(localStorage.getItem(CARD_KEY)||"[]");return Array.isArray(v)?v:[]}catch{return[]}}
function norm(v?:string){return String(v||"").trim().replace(/\s+/g," ").toLowerCase()}
function resolveOpenCard(modal:HTMLElement){const player=modal.querySelector<HTMLElement>(".cs-detail-head h2")?.textContent?.trim()||"",meta=modal.querySelector<HTMLElement>(".cs-detail-head p")?.textContent?.trim()||"";if(!player)return null;const list=readCards(),exact=list.filter(c=>norm(c.player)===norm(player)&&(!meta||norm(c.meta)===norm(meta)));if(exact.length===1)return exact[0];const same=list.filter(c=>norm(c.player)===norm(player));return same.length===1?same[0]:null}
function pct(v:number|null|undefined){return v==null?"—":`${v>=0?"+":""}${v.toFixed(1)}%`}
function statusTone(status:string){return status==="RAPID GROWTH"?"danger":status==="GROWING"?"warn":status==="DECLINING"?"positive":"neutral"}

export default function GradingPopulationLayer(){
 const[host,setHost]=useState<HTMLElement|null>(null),[cardId,setCardId]=useState<number|null>(null),[version,setVersion]=useState(0),[provider,setProvider]=useState<GradingProvider>("PSA"),[grade,setGrade]=useState("10"),[totalPop,setTotalPop]=useState(""),[higherPop,setHigherPop]=useState("");
 useEffect(()=>{const attach=()=>{const modal=document.querySelector<HTMLElement>(".cs-detail-modal");if(!modal){setHost(null);setCardId(null);return}const card=resolveOpenCard(modal);if(!card){setHost(null);setCardId(null);return}setCardId(card.id);let h=modal.querySelector<HTMLElement>("#cs-grading-pop-host");if(!h){h=document.createElement("div");h.id="cs-grading-pop-host";const market=modal.querySelector("#cs-market-context-host");if(market)market.insertAdjacentElement("afterend",h);else modal.appendChild(h)}setHost(h)};attach();const obs=new MutationObserver(attach);obs.observe(document.body,{childList:true,subtree:true});const refresh=()=>setVersion(v=>v+1);window.addEventListener("cardsignal:grading-population-changed",refresh);window.addEventListener("cardsignal:user-cards-changed",refresh);return()=>{obs.disconnect();window.removeEventListener("cardsignal:grading-population-changed",refresh);window.removeEventListener("cardsignal:user-cards-changed",refresh)}},[]);
 const card=useMemo(()=>cardId==null?null:readCards().find(c=>c.id===cardId)||null,[cardId,version]);
 const history=useMemo(()=>readPopulationHistory(),[version]);
 const cardHistory=useMemo(()=>card?history.filter(x=>x.cardId===card.id).sort((a,b)=>new Date(b.capturedAt).getTime()-new Date(a.capturedAt).getTime()):[],[card,history]);
 const current=cardHistory[0]||null;
 const trend=card?populationTrend(history,card.id,current?.provider,current?.grade):null;
 const d30=card&&current?nearestTrend(history,card.id,30,current.provider,current.grade):null,d90=card&&current?nearestTrend(history,card.id,90,current.provider,current.grade):null;
 useEffect(()=>{if(card?.grader)setProvider(card.grader.toUpperCase() as GradingProvider);if(card?.grade)setGrade(String(card.grade))},[card?.id]);
 const save=()=>{if(!card)return;const n=Number(totalPop);if(!Number.isFinite(n)||n<0)return;const h=higherPop.trim()===""?null:Number(higherPop);const snap:PopulationSnapshot={id:`${card.id}-${provider}-${grade}-${Date.now()}`,cardId:card.id,provider,grade:grade.trim()||"Unknown",totalPop:n,higherPop:Number.isFinite(h as number)?h:null,capturedAt:new Date().toISOString(),source:"MANUAL",sourceNote:"Manual baseline until provider population API is available"};writePopulationHistory([snap,...history]);setTotalPop("");setHigherPop("");setVersion(v=>v+1)};
 if(!host||!card)return null;
 return createPortal(<section className="cs-gp-panel"><div className="cs-gp-head"><div><span>GRADING POPULATION</span><b>Exact-card supply monitor</b></div><div className={`cs-gp-status ${statusTone(trend?.status||"NO DATA")}`}>{trend?.status||"NO DATA"}</div></div>
  {current?<><div className="cs-gp-grid"><div><small>PROVIDER / GRADE</small><strong>{current.provider} {current.grade}</strong><span>{current.source==="MANUAL"?"manual snapshot":"provider API"}</span></div><div><small>CURRENT POP</small><strong>{current.totalPop.toLocaleString()}</strong><span>{trend?.prior?`${trend.change!>=0?"+":""}${trend.change} since prior snapshot`:"baseline established"}</span></div><div><small>30D GROWTH</small><strong>{d30?pct(d30.pct):"—"}</strong><span>{d30?`${d30.change>=0?"+":""}${d30.change} slabs":"need older same-grade snapshot"}</span></div><div><small>90D GROWTH</small><strong>{d90?pct(d90.pct):"—"}</strong><span>{d90?`${d90.change>=0?"+":""}${d90.change} slabs":"need older same-grade snapshot"}</span></div></div><div className="cs-gp-read">{trend?.status==="RAPID GROWTH"?"High-grade supply is expanding quickly. For modern cards, accelerating population can add price pressure if demand does not keep pace.":trend?.status==="GROWING"?"Population is growing. Watch whether sales velocity and price can absorb the added graded supply.":trend?.status==="STABLE"?"Population is relatively stable between saved snapshots.":trend?.status==="DECLINING"?"The latest value is below the prior snapshot. Verify the source because certified population counts normally do not materially decline.":"Record another snapshot later to establish a population trend."}</div></>:<div className="cs-gp-empty"><b>No grading-population baseline yet</b><span>Snapshots are stored against this exact saved card ID, not merely the player name.</span></div>}
  <div className="cs-gp-form"><label><span>PROVIDER</span><select value={provider} onChange={e=>setProvider(e.target.value as GradingProvider)}><option>PSA</option><option>BGS</option><option>SGC</option><option>CGC</option><option>OTHER</option></select></label><label><span>GRADE</span><input value={grade} onChange={e=>setGrade(e.target.value)} placeholder="10"/></label><label><span>TOTAL POP</span><input type="number" min="0" value={totalPop} onChange={e=>setTotalPop(e.target.value)} placeholder="e.g. 1242"/></label><label><span>HIGHER GRADE POP</span><input type="number" min="0" value={higherPop} onChange={e=>setHigherPop(e.target.value)} placeholder="optional"/></label><button onClick={save}>SAVE SNAPSHOT</button></div>
  <div className="cs-gp-note">30D and 90D comparisons now stay inside the same card, provider and grade. No cross-parallel or cross-grade population history is allowed.</div>
  <style jsx global>{`.cs-gp-panel{margin:12px 0;padding:14px;border:1px solid rgba(178,158,255,.14);border-radius:11px;background:rgba(19,13,38,.38)}.cs-gp-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.cs-gp-head span,.cs-gp-head b{display:block}.cs-gp-head span{color:#b8a8ff;font-size:8px;font-weight:900;letter-spacing:.13em}.cs-gp-head b{margin-top:3px;color:#7f94a4;font-size:8px}.cs-gp-status{padding:6px 9px;border:1px solid rgba(134,155,176,.18);border-radius:7px;color:#92a8b4;font-size:7px;font-weight:900}.cs-gp-status.danger{color:#ff8997;border-color:rgba(255,105,125,.3)}.cs-gp-status.warn{color:#efc86e;border-color:rgba(239,200,110,.28)}.cs-gp-status.positive{color:#65eda7;border-color:rgba(82,230,155,.28)}.cs-gp-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.cs-gp-grid>div{padding:9px;border:1px solid rgba(153,134,224,.09);border-radius:8px;background:rgba(8,20,35,.55)}.cs-gp-grid small,.cs-gp-grid strong,.cs-gp-grid span{display:block}.cs-gp-grid small{color:#657f90;font-size:6px;font-weight:900}.cs-gp-grid strong{margin:4px 0 2px;font-size:13px}.cs-gp-grid span{color:#6c8796;font-size:7px}.cs-gp-read{margin-top:8px;padding:9px;border-left:2px solid #9f8df0;background:rgba(115,87,205,.06);color:#8fa6b3;font-size:8px;line-height:1.45}.cs-gp-empty{padding:15px;text-align:center;border:1px dashed rgba(153,134,224,.13);border-radius:8px}.cs-gp-empty b,.cs-gp-empty span{display:block}.cs-gp-empty b{font-size:10px}.cs-gp-empty span{margin-top:4px;color:#728c9b;font-size:8px;line-height:1.45}.cs-gp-form{display:grid;grid-template-columns:130px 90px 130px 150px auto;gap:7px;align-items:end;margin-top:10px}.cs-gp-form label span{display:block;margin-bottom:3px;color:#647f90;font-size:6px;font-weight:900}.cs-gp-form input,.cs-gp-form select{width:100%;height:32px;padding:0 8px;border:1px solid rgba(153,134,224,.13);border-radius:6px;background:#081724;color:#dcebf2;font-size:8px}.cs-gp-form button{height:32px;padding:0 10px;border:1px solid rgba(160,140,244,.25);border-radius:6px;background:rgba(116,88,210,.08);color:#c4b8ff;font-size:7px;font-weight:900;cursor:pointer}.cs-gp-note{margin-top:8px;color:#5e7988;font-size:7px;line-height:1.4}@media(max-width:760px){.cs-gp-grid{grid-template-columns:1fr 1fr}.cs-gp-form{grid-template-columns:1fr 1fr}.cs-gp-form button{grid-column:1/-1}}`}</style>
 </section>,host);
}
