"use client";

import { useEffect } from "react";

type AlertKind="buy"|"sell"|"watch"|"info"|"resolved";
type Alert={id:string;player:string;createdAt:string;kind:AlertKind;title:string;detail:string;read?:boolean};
type PortfolioSnapshot={scannedAt:string;portfolioValue:number;ownedCount:number;pricedCount:number;evidenceCount:number;buy:number;sell:number;watch:number;hold:number;needsData:number};
const ALERTS_KEY="cardsignal-alerts",PORTFOLIO_HISTORY_KEY="cardsignal-portfolio-history";
function read<T>(key:string,fallback:T):T{try{return(JSON.parse(localStorage.getItem(key)||"")??fallback)as T}catch{return fallback}}
function safe(v:string){return v.replace(/[<>&]/g,m=>({"<":"&lt;",">":"&gt;","&":"&amp;"}[m]!))}
function money(v:number){return `$${v.toLocaleString(undefined,{maximumFractionDigits:0})}`}
function renderAlerts(){const panel=document.querySelector<HTMLElement>(".alerts-panel");if(!panel)return;panel.querySelectorAll(".alert").forEach(n=>n.remove());const alerts=read<Alert[]>(ALERTS_KEY,[]).slice(0,3);if(!alerts.length){const a=document.createElement("div");a.className="alert info";a.innerHTML=`<i>◎</i><div><b>No change alerts yet</b><p>Run Portfolio Pulse again later to compare against the current baseline.</p><small>Waiting for repeated scans</small></div>`;panel.appendChild(a);return;}for(const item of alerts){const cls=item.kind==="sell"?"sell":item.kind==="buy"?"buy":"info";const icon=item.kind==="sell"?"▼":item.kind==="buy"?"▲":item.kind==="resolved"?"✓":"◎";const a=document.createElement("div");a.className=`alert ${cls}`;a.innerHTML=`<i>${icon}</i><div><b>${safe(item.title)}</b><p>${safe(item.player)} · ${safe(item.detail)}</p><small>${new Date(item.createdAt).toLocaleString()}</small></div>`;panel.appendChild(a);}}
function renderTrend(){const area=document.querySelector<HTMLElement>(".trend-panel .chart-area");if(!area)return;const raw=read<PortfolioSnapshot[]>(PORTFOLIO_HISTORY_KEY,[]);const history=[...raw].sort((a,b)=>new Date(a.scannedAt).getTime()-new Date(b.scannedAt).getTime()).slice(-30);const title=document.querySelector<HTMLElement>(".trend-panel .section-title small");if(history.length<2){area.innerHTML=`<div class="cs-trend-empty"><b>Portfolio trend history starts after repeated scans</b><span>${history.length?"One portfolio snapshot is saved. Run another scan later to begin a truthful trend line.":"No saved portfolio snapshots yet. The next Portfolio Pulse scan becomes your baseline."}</span></div>`;if(title)title.textContent="Historical snapshots only";return;}const values=history.map(h=>h.portfolioValue);const min=Math.min(...values),max=Math.max(...values),spread=Math.max(1,max-min);const width=700,height=180,pad=12;const points=history.map((h,i)=>{const x=pad+(i/(history.length-1))*(width-pad*2);const y=height-pad-((h.portfolioValue-min)/spread)*(height-pad*2);return`${x.toFixed(1)},${y.toFixed(1)}`}).join(" ");const first=history[0],last=history.at(-1)!;const delta=first.portfolioValue?((last.portfolioValue-first.portfolioValue)/first.portfolioValue)*100:0;area.innerHTML=`<div class="cs-real-trend-summary"><b>${money(last.portfolioValue)}</b><span class="${delta<0?"negative":"positive"}">${delta>=0?"+":""}${delta.toFixed(1)}% since first saved snapshot</span><small>${history.length} portfolio snapshots</small></div><svg viewBox="0 0 700 180" preserveAspectRatio="none" aria-label="Saved portfolio value trend"><polyline fill="none" stroke="${delta<0?"#ff6f82":"#55efa2"}" stroke-width="4" points="${points}" vector-effect="non-scaling-stroke"/></svg><div class="cs-real-trend-days"><span>${new Date(first.scannedAt).toLocaleDateString()}</span><span>${new Date(last.scannedAt).toLocaleDateString()}</span></div>`;if(title)title.textContent=`${history.length} saved snapshots · ${new Date(last.scannedAt).toLocaleString()}`;}
export default function HistoryHomeBridge(){useEffect(()=>{const render=()=>{renderAlerts();renderTrend();};const timer=window.setTimeout(render,50);window.addEventListener("cardsignal:history-changed",render);window.addEventListener("cardsignal:user-cards-changed",render);return()=>{window.clearTimeout(timer);window.removeEventListener("cardsignal:history-changed",render);window.removeEventListener("cardsignal:user-cards-changed",render);};},[]);return<style jsx global>{`.cs-real-trend-summary{display:flex;align-items:baseline;gap:12px;margin:8px 0 6px}.cs-real-trend-summary b{font-size:22px}.cs-real-trend-summary span{font-size:10px;font-weight:800}.cs-real-trend-summary small{margin-left:auto;color:#678799;font-size:8px}.trend-panel .chart-area>.cs-real-trend-summary+svg{width:100%;height:150px;overflow:visible}.cs-real-trend-days{display:flex;justify-content:space-between;color:#5f7f91;font-size:8px}.cs-trend-empty{height:190px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:30px;border:1px dashed rgba(80,190,225,.16);border-radius:10px;background:rgba(5,20,32,.34)}.cs-trend-empty b{color:#c5dce7;font-size:13px}.cs-trend-empty span{max-width:520px;margin-top:8px;color:#69899a;font-size:10px;line-height:1.55}`}</style>}
