"use client";

import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";
import {getCardMarketContext} from "./card-market-context";

type MarketScan={scannedAt?:string;velocity?:number|null;change7d?:number|null;acceptedCount?:number;currentMedian?:number|null};
type Card={id:number;player:string;meta?:string;year?:string;setName?:string;cardNumber?:string;variant?:string;grader?:string;grade?:string;marketScan?:MarketScan};
type Snap={cardId:number;scannedAt:string;velocity:number|null;change7d:number|null;acceptedCount:number;currentMedian:number|null};
const CARD_KEY="cardsignal-added-cards",HISTORY_KEY="cardsignal-scan-history";
function read<T>(k:string,f:T):T{try{const v=JSON.parse(localStorage.getItem(k)||"");return(v??f)as T}catch{return f}}
function norm(v?:string){return String(v||"").trim().replace(/\s+/g," ").toLowerCase()}
function resolveOpenCard(){const modal=document.querySelector<HTMLElement>(".cs-detail-modal");if(!modal)return null;const player=modal.querySelector<HTMLElement>(".cs-detail-head h2")?.textContent?.trim()||"",meta=modal.querySelector<HTMLElement>(".cs-detail-head p")?.textContent?.trim()||"";if(!player)return null;const list=read<Card[]>(CARD_KEY,[]),exact=list.filter(c=>norm(c.player)===norm(player)&&(!meta||norm(c.meta)===norm(meta)));if(exact.length===1)return exact[0];const same=list.filter(c=>norm(c.player)===norm(player));return same.length===1?same[0]:null}
function pct(v:number|null){return v==null?"—":`${v>=0?"+":""}${v.toFixed(0)}%`}
function velocityContext(history:Snap[],card:Card){const rows=history.filter(x=>x.cardId===card.id&&x.velocity!=null).sort((a,b)=>new Date(b.scannedAt).getTime()-new Date(a.scannedAt).getTime());const current=card.marketScan?.velocity??rows[0]?.velocity??null;const prior=rows.find((x,i)=>i>0&&x.velocity!=null)?.velocity??null;if(current==null||prior==null)return{current,prior,delta:null,label:"BASELINE" as const};const d=prior===0?(current>0?100:null):((current-prior)/Math.abs(prior))*100;const label=d==null?"BASELINE":d>=30?"ACCELERATING":d<=-30?"COOLING":"STABLE";return{current,prior,delta:d,label}}

export default function MarketContextLayer(){
 const[host,setHost]=useState<HTMLElement|null>(null),[cardId,setCardId]=useState<number|null>(null),[version,setVersion]=useState(0);
 useEffect(()=>{const attach=()=>{const modal=document.querySelector<HTMLElement>(".cs-detail-modal");if(!modal){setHost(null);setCardId(null);return}const card=resolveOpenCard();if(!card){setHost(null);setCardId(null);return}setCardId(card.id);let h=modal.querySelector<HTMLElement>("#cs-market-context-host");if(!h){h=document.createElement("div");h.id="cs-market-context-host";const catalyst=modal.querySelector("#cs-detail-catalyst-host"),sales=modal.querySelector(".cs-md-sales");if(catalyst)catalyst.insertAdjacentElement("afterend",h);else if(sales)modal.insertBefore(h,sales);else modal.appendChild(h)}setHost(h)};attach();const obs=new MutationObserver(attach);obs.observe(document.body,{childList:true,subtree:true});const refresh=()=>setVersion(v=>v+1);window.addEventListener("cardsignal:user-cards-changed",refresh);window.addEventListener("storage",refresh);return()=>{obs.disconnect();window.removeEventListener("cardsignal:user-cards-changed",refresh);window.removeEventListener("storage",refresh)}},[]);
 const data=useMemo(()=>{if(cardId==null)return null;const card=read<Card[]>(CARD_KEY,[]).find(c=>c.id===cardId);if(!card)return null;const history=read<Snap[]>(HISTORY_KEY,[]);return{card,ctx:getCardMarketContext(card),vel:velocityContext(history,card)}},[cardId,version]);
 if(!host||!data)return null;const{ctx,vel}=data;
 return createPortal(<article className="cs-mctx"><div className="cs-mctx-head"><div><span>MARKET CONTEXT</span><b>Exact-card segment & demand behavior</b></div><strong className={`sens ${ctx.sensitivity.toLowerCase()}`}>{ctx.sensitivity} SENSITIVITY</strong></div><div className="cs-mctx-grid"><div><small>ERA</small><b>{ctx.era}</b></div><div><small>CARD PROFILE</small><b>{ctx.role}</b></div><div><small>SUPPLY CLUE</small><b>{ctx.supplyHint}</b></div><div><small>GRADING</small><b>{ctx.graded?"GRADED":"RAW / UNKNOWN"}</b></div><div className={`velocity ${vel.label.toLowerCase()}`}><small>VELOCITY TREND</small><b>{vel.label}</b><span>{vel.current==null?"No velocity history yet":vel.prior==null?`Current ${vel.current} · baseline`:`${vel.prior} → ${vel.current} · ${pct(vel.delta)}`}</span></div></div><p>{vel.label==="ACCELERATING"?"Sales velocity is rising faster than this exact card's prior saved scan. If price has not moved similarly, this may be an early demand signal worth reviewing.":vel.label==="COOLING"?"Sales velocity has fallen materially for this exact card versus its prior saved scan. Treat weakening demand as context, not a standalone sell signal.":"Card segment and velocity context are shown separately from the CardSignal Score until their predictive value is validated."}</p>{ctx.reasons.length>0&&<div className="cs-mctx-reasons">{ctx.reasons.map(r=><span key={r}>{r}</span>)}</div>}<style jsx global>{`.cs-mctx{margin:14px 0;padding:14px;border:1px solid rgba(107,168,255,.13);border-radius:11px;background:rgba(8,18,38,.58)}.cs-mctx-head{display:flex;align-items:end;justify-content:space-between;gap:12px;margin-bottom:9px}.cs-mctx-head span,.cs-mctx-head b{display:block}.cs-mctx-head span{color:#8eaeff;font-size:8px;font-weight:900;letter-spacing:.14em}.cs-mctx-head b{margin-top:3px;font-size:12px}.cs-mctx-head .sens{padding:5px 8px;border:1px solid rgba(142,174,255,.22);border-radius:7px;color:#aabfff;font-size:7px;letter-spacing:.08em}.cs-mctx-head .sens.high{color:#67efa8;border-color:rgba(103,239,168,.25)}.cs-mctx-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.cs-mctx-grid>div{padding:9px;border:1px solid rgba(94,145,220,.09);border-radius:8px;background:rgba(5,17,31,.62)}.cs-mctx-grid small,.cs-mctx-grid b,.cs-mctx-grid span{display:block}.cs-mctx-grid small{color:#667d9f;font-size:6px;font-weight:900}.cs-mctx-grid b{margin-top:4px;font-size:8px}.cs-mctx-grid span{margin-top:3px;color:#7187a0;font-size:6px}.cs-mctx-grid .velocity.accelerating b{color:#61efa5}.cs-mctx-grid .velocity.cooling b{color:#ff8997}.cs-mctx p{margin:9px 0 0;color:#72879d;font-size:7px;line-height:1.45}.cs-mctx-reasons{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.cs-mctx-reasons span{padding:4px 6px;border-radius:999px;background:rgba(110,143,207,.08);color:#8298b5;font-size:6px}@media(max-width:760px){.cs-mctx-grid{grid-template-columns:1fr 1fr}.cs-mctx-grid .velocity{grid-column:1/-1}}`}</style></article>,host)
}
