"use client";

import { useMemo, useState } from "react";

type Listing={id:string;title:string;price:number|null;currency:string;url:string;condition:string;buyingOptions:string[]};
type Snapshot={cardId:number;scannedAt:string;provider:string;query:string;rawTotal:number;fetchedCount:number;acceptedCount:number;rejectedCount:number;lowestAsk:number|null;medianAsk:number|null;highestAsk:number|null;listings:Listing[]};
type ApiResponse=Partial<Snapshot>&{ok:boolean;error?:string;configured?:boolean};
type Props={cardId:number;player:string;year?:string;setName?:string;cardNumber?:string;variant?:string;soldMedian?:number|null};

const HISTORY_KEY="cardsignal-supply-history",CARD_KEY="cardsignal-added-cards";
function readHistory():Snapshot[]{try{const v=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]");return Array.isArray(v)?v:[]}catch{return[]}}
function money(v:number|null|undefined){return v==null?"—":`$${v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function deltaPct(now:number|null,prior:number|null){return now!=null&&prior!=null&&prior!==0?((now-prior)/prior)*100:null}
function pct(v:number|null){return v==null?"—":`${v>=0?"+":""}${v.toFixed(1)}%`}

export default function SupplyWatchPanel({cardId,player,year,setName,cardNumber,variant,soldMedian}:Props){
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 const [version,setVersion]=useState(0);
 const history=useMemo(()=>readHistory().filter(x=>x.cardId===cardId).sort((a,b)=>new Date(b.scannedAt).getTime()-new Date(a.scannedAt).getTime()),[cardId,version]);
 const current=history[0]||null,previous=history[1]||null;
 const inventoryDelta=current&&previous?deltaPct(current.acceptedCount,previous.acceptedCount):null;
 const askDelta=current&&previous?deltaPct(current.medianAsk,previous.medianAsk):null;
 const askVsSold=current?.medianAsk!=null&&soldMedian!=null&&soldMedian>0?((current.medianAsk-soldMedian)/soldMedian)*100:null;
 const pressure=!current?"NO DATA":!previous?"BASELINE":inventoryDelta!=null&&inventoryDelta<=-15?"TIGHTENING":inventoryDelta!=null&&inventoryDelta>=15?"LOOSENING":"STABLE";
 const scan=async()=>{if(busy)return;setBusy(true);setError("");const p=new URLSearchParams({player,year:year||"",set:setName||"",cardNumber:cardNumber||"",variant:variant||""});try{const r=await fetch(`/api/supply-watch?${p.toString()}`,{cache:"no-store"});const j=await r.json() as ApiResponse;if(!r.ok||!j.ok)throw new Error(j.error||"Supply scan failed");const snap:Snapshot={cardId,scannedAt:String(j.scannedAt||new Date().toISOString()),provider:String(j.provider||"eBay Browse API"),query:String(j.query||""),rawTotal:Number(j.rawTotal||0),fetchedCount:Number(j.fetchedCount||0),acceptedCount:Number(j.acceptedCount||0),rejectedCount:Number(j.rejectedCount||0),lowestAsk:j.lowestAsk??null,medianAsk:j.medianAsk??null,highestAsk:j.highestAsk??null,listings:Array.isArray(j.listings)?j.listings:[]};const all=readHistory().filter(x=>!(x.cardId===cardId&&x.scannedAt===snap.scannedAt));localStorage.setItem(HISTORY_KEY,JSON.stringify([snap,...all].slice(0,1500)));try{const cards=JSON.parse(localStorage.getItem(CARD_KEY)||"[]");if(Array.isArray(cards)){localStorage.setItem(CARD_KEY,JSON.stringify(cards.map((c:{id?:number})=>c.id===cardId?{...c,supplySnapshot:{scannedAt:snap.scannedAt,provider:snap.provider,activeAccepted:snap.acceptedCount,rawTotal:snap.rawTotal,lowestAsk:snap.lowestAsk,medianAsk:snap.medianAsk}}:c)));window.dispatchEvent(new Event("cardsignal:user-cards-changed"));}}catch{}setVersion(v=>v+1)}catch(e){setError(e instanceof Error?e.message:"Supply scan failed")}finally{setBusy(false)}};
 return <article className="cs-sw-panel"><div className="cs-sw-head"><div><span>SUPPLY WATCH</span><b>Active-market pressure</b></div><div className={`cs-sw-status ${pressure.toLowerCase()}`}>{pressure}</div></div>
  {!current?<div className="cs-sw-empty"><b>No active-supply snapshot yet</b><span>Connect eBay Browse and scan this card to begin tracking active listings and asking prices.</span><button onClick={scan} disabled={busy}>{busy?"SCANNING ACTIVE LISTINGS…":"◉ SCAN ACTIVE SUPPLY"}</button></div>:<><div className="cs-sw-grid"><div><small>ACCEPTED ACTIVE LISTINGS</small><strong>{current.acceptedCount}</strong><span>{current.fetchedCount} fetched · {current.rawTotal} raw eBay matches</span></div><div><small>LOWEST ASK</small><strong>{money(current.lowestAsk)}</strong><span>{askVsSold==null?"sold median comparison unavailable":`${pct(askVsSold)} vs sold median`}</span></div><div><small>MEDIAN ASK</small><strong>{money(current.medianAsk)}</strong><span>{previous?`${pct(askDelta)} vs prior supply scan`:"baseline established"}</span></div><div><small>INVENTORY CHANGE</small><strong className={inventoryDelta!=null&&inventoryDelta<0?"positive":inventoryDelta!=null&&inventoryDelta>0?"negative":""}>{previous?pct(inventoryDelta):"—"}</strong><span>{previous?`${previous.acceptedCount} → ${current.acceptedCount} accepted listings`:"run another scan later"}</span></div></div><div className="cs-sw-actions"><button onClick={scan} disabled={busy}>{busy?"SCANNING ACTIVE LISTINGS…":"◉ REFRESH SUPPLY"}</button><span>Last checked {new Date(current.scannedAt).toLocaleString()}</span></div>{current.listings.length>0&&<div className="cs-sw-list"><div className="cs-sw-list-title">LOWEST ACCEPTED ACTIVE LISTINGS</div>{[...current.listings].sort((a,b)=>(a.price??Infinity)-(b.price??Infinity)).slice(0,5).map((l,i)=><div key={`${l.id}-${i}`}><div><strong>{l.title}</strong><span>{l.condition||"Condition not supplied"} · {l.buyingOptions.join(" / ")||"Active listing"}</span></div><b>{money(l.price)}</b></div>)}</div>}</>}
  {error&&<div className="cs-sw-error">{error}</div>}
  <div className="cs-sw-note">Supply Watch uses active eBay Browse listings, not completed sales. The accepted count is identity-filtered from the fetched search results; when eBay reports more than the fetched limit, it should be treated as a sample rather than the entire market.</div>
  <style jsx global>{`.cs-sw-panel{margin-top:10px;padding:15px;border:1px solid rgba(77,188,228,.12);border-radius:11px;background:rgba(5,20,32,.62)}.cs-sw-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:11px}.cs-sw-head span{display:block;color:#55dfff;font-size:8px;font-weight:900;letter-spacing:.12em}.cs-sw-head b{display:block;margin-top:3px;color:#8ca8b7;font-size:8px}.cs-sw-status{padding:6px 9px;border:1px solid rgba(85,215,242,.2);border-radius:7px;color:#7fdcf4;font-size:7px;font-weight:900;letter-spacing:.08em}.cs-sw-status.tightening{color:#64efaa;border-color:rgba(73,238,157,.3)}.cs-sw-status.loosening{color:#ff8494;border-color:rgba(255,105,125,.3)}.cs-sw-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.cs-sw-grid>div{padding:11px;border:1px solid rgba(77,188,228,.1);border-radius:9px;background:rgba(7,25,39,.7)}.cs-sw-grid small{display:block;color:#668899;font-size:6px;font-weight:900;letter-spacing:.08em}.cs-sw-grid strong{display:block;margin:5px 0 3px;font-size:18px}.cs-sw-grid span{color:#688797;font-size:7px}.cs-sw-actions{display:flex;align-items:center;gap:12px;margin-top:10px}.cs-sw-actions button,.cs-sw-empty button{height:35px;padding:0 13px;border:1px solid rgba(66,239,154,.38);border-radius:8px;background:rgba(43,194,122,.1);color:#9affc5;font-size:7px;font-weight:900;letter-spacing:.08em;cursor:pointer}.cs-sw-actions button:disabled,.cs-sw-empty button:disabled{opacity:.45}.cs-sw-actions span{color:#607f90;font-size:7px}.cs-sw-empty{min-height:120px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:18px;border:1px dashed rgba(77,188,228,.13);border-radius:9px}.cs-sw-empty b{font-size:11px}.cs-sw-empty span{max-width:520px;margin:5px 0 11px;color:#688797;font-size:8px;line-height:1.5}.cs-sw-list{margin-top:11px;border-top:1px solid rgba(78,183,224,.08);padding-top:8px}.cs-sw-list-title{margin-bottom:4px;color:#66899a;font-size:7px;font-weight:900;letter-spacing:.08em}.cs-sw-list>div:not(.cs-sw-list-title){display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;padding:7px 2px;border-top:1px solid rgba(78,183,224,.06)}.cs-sw-list strong,.cs-sw-list span{display:block}.cs-sw-list strong{font-size:8px}.cs-sw-list span{margin-top:2px;color:#668797;font-size:6px}.cs-sw-list>div>b{font-size:9px}.cs-sw-error{margin-top:10px;padding:9px;border:1px solid rgba(255,100,120,.25);border-radius:8px;background:rgba(160,35,50,.1);color:#ff9cab;font-size:8px}.cs-sw-note{margin-top:10px;color:#5f7d8e;font-size:7px;line-height:1.45}.positive{color:#5eeaa0!important}.negative{color:#ff7b8b!important}@media(max-width:760px){.cs-sw-grid{grid-template-columns:1fr 1fr}.cs-sw-actions{align-items:flex-start;flex-direction:column}}`}</style>
 </article>
}
